# This is a sample build configuration for Go.
# Check our guides at https://confluence.atlassian.com/x/5Q4SMw for more examples.
# Only use spaces to indent your .yml configuration.
# -----
# You can specify a custom docker image from Docker Hub as your build environment.
image: golang:1.9

pipelines:
  default:
    - step:
        script: # Modify the commands below to build your repository.
          # - apt install upx-ucl
          # - PACKAGE_PATH="${GOPATH}/src/bitbucket.org/${BITBUCKET_REPO_OWNER}/${BITBUCKET_REPO_SLUG}"
          - PACKAGE_PATH="${GOPATH}/src/extract-blocks"
          - mkdir -pv "${PACKAGE_PATH}"
          - tar -cO --exclude-vcs --exclude=bitbucket-pipelines.yml . | tar -xv -C "${PACKAGE_PATH}"
          - cd "${PACKAGE_PATH}"
          # - go get -v
          # - go build -v
          - go build -v -o $(basename $PWD) main.go
          - ./bin/upx --best --lzma $(basename $PWD)
          - ./$(basename $PWD) run -v demo.xlsx
          - go test -v -short cmd_test.go
          - curl -X POST "https://${BB_AUTH_STRING}@api.bitbucket.org/2.0/repositories/${BITBUCKET_REPO_OWNER}/${BITBUCKET_REPO_SLUG}/downloads" --form files=@"$(basename $PWD)"
